theme: minima
title: "Andrew Miele's Professional Portfolio"
author: "Andrew Miele"
description: "Mechanical Engineering with Aerospace concentration | University of Connecticut | GPA: 3.444 | Skills in Python, SolidWorks, ANSYS, Matlab, and more."
